language: python
python:
- '3.8'
install:
- pip install pipenv
- pipenv install
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=purbeurre_project.settings.travis
  global:
  - secure: iGRpYlT3l+3f15lb/CevPQOb3Why4Et4w1x4umMtODjaIEH/q+fL6+JN7xyqjAAKA5/S3L/rBRyueQLq9P0iMJ0/CjTqzbuJwCEgiLm32Qscu937o4PsGoW1Y8SPWKaZs6SjrDEfMKETCrpeJ8dPvqR78KcHNWT3J2s+LW17uwVcF/grK8vZboOg6XU3MgWVmssdP8JFUyIDqj3oYNSJMGgUGqf5vz09ra/aw4TgzeHbODCrdI5snUtPTx5rW+n0nvDP2BqJeVZzJvT7Mv9cpwqBQvusipULyjyis5Myn7ajxTYU+mK11iHeku9KP5OtHK+Cadt/SaJb/NahtwRquKx4dC+yKwBmsFaO2FDbnmvpswoVwd19qKwthniqcKD3z2iL9SiBQ849oiA49PA8abliHF+dsfBhoePtw1pOcP4MfrJR0WRbM0dHjn6otUm5PLAm9uALV8JBJ6lU/fDvbglarYbbcRknU3qHDY2mI7K6+lynAXkX7M/ECzCKxlGl4wuJWX5Z86HwLx0qrCEzRKQcFu4ZPj2/WH2jTAabC3rrIhXLSL4Nh2jV3g9rF7wrjq26abXBoyxO0xCdQ9mSGpzUQODm5sgYNIqELIAX/twY9vRNSxdrJc1ODbxAdYd2L4G21EPYrOvqY3jeTEkPU0E0i96zQ1T8Z+L8DR7Z94Q=
  - secure: lYzwhyJPFcMk9G5kDoYWAJDx2pSYlNZ0Ecxjj7/DwUGRhP9RfsgdPY7ZYhoBHcbMVvr+ZucExebOlabESw4f71m1574BW6LrxKBCfwlu+sokL3d3olkHFYYkN6ac8clNm63I11rs1mXdHXzkp06h4wYAkP2k2hdextqo+RaO4UBaBCMBNOZpUEuRbAZ77C/N4/5SxUYc4HyEXoU7MsMmnfPrJ3yg35R9oaHaQAIt+vXPzzxn7uP2JV61HP5bJ4uKHwTww60ecXD2E6ssypMAwxfWw5aXCtMLQnYSk8cuC7QvwdfBvE20OGy35a2KO15ZLfA130M4W/UN1OlLjwe/vunp6vR8ULipD6nuW8u5Osed1Wap+x8E0fH/dzHgEDF6jmucwzEIym3uMJZQlgEofdnt8jQaSjyv1Jj7oQ0fAW4rGpsJ1n9WwSTRGlD3asv3MqccB/9S5fNND6U78lrLzREgeKLr1rQ2aj3G/SwmpEhiSDaaO4pD/UqAM4UXnp9Uo4oiXkJ43mQBwUXVpYRNwJwYnTdSxIcN5FU8Rr4CB3e0VZPOh2bTRan4cxe/EA+ueEpd0FzM5T1H+rtppoNnv4HpWTihJDlqZ5fFd41klt/o7+VMTWE9bCiYEnVgecEXnXF9hC7inGIbxgSKm2jB/u0pAM8BFyfYHVYjrGvum7I=
script:
- python manage.py test
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: ssh -i /tmp/deploy_rsa $USERNAME@$HOSTNAME "cd purbeurre; git pull"
addons:
  ssh_known_hosts: 46.101.143.60
  #$HOSTNAME
