language: python
python:
- '3.8'
install:
- pip install pipenv
- pipenv install
env: DJANGO_SETTINGS_MODULE=purbeurre_project.settings.travis
script:
- python manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
